version: 2

sphinx:
  configuration: docs/conf.py

# Image to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.89"
  apt_packages:
    - pandoc

python:
  install:
    - method: pip
      path: .[docs]
