FROM nvidia/cuda:10.1-cudnn7-devel
#FROM tacc/tacc-ubuntu18-mvapich2.3-ib

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y gcc wget procps net-tools libffi-dev &&\
    apt-get autoclean -y && apt-get clean -y && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh -O ./miniconda.sh && \
    /bin/bash miniconda.sh -b -p/opt/conda  && \
    rm miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc

ENV PATH /opt/conda/bin:$PATH
COPY ./requirements.yml ./requirements.yml

ARG JAXLIB_VERSION=0.1.64+cuda101
ARG JUPYTER
ENV PIP_FIND_LINKS https://storage.googleapis.com/jax-releases/jax_releases.html
RUN conda env update -n base -f requirements.yml
RUN /bin/bash -c 'if [[ -n "$JUPYTER" ]]; then conda install -c conda-forge jupyterlab=3 seaborn matplotlib; fi' && \
    pip install jax jaxlib==$JAXLIB_VERSION && \
    conda clean -afy

COPY ./ /pyCRM
ENV PYTHONPATH /pyCRM:$PYTHONPATH
WORKDIR /pyCRM
